=== rachidho/technomaker-xml-tp1/xml-validation/descripteur.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="animaux">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="chiens"/>
        <xs:element minOccurs="0" ref="chats"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="chiens">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="chien"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="chien">
    <xs:complexType mixed="true">
      <xs:attribute name="numeroCollier" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="chats">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="chat"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="chat">
    <xs:complexType mixed="true">
      <xs:attribute name="numeroCollier" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== rachidho/technomaker-xml-tp1/xml-donnees/exemple.xml
<?xml version="1.0" encoding="UTF-8"?>
<animaux xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="descripteur.xsd">
	
	<chiens>
		<chien numeroCollier="C112233">Medor</chien>
		<!-- Chien inconnu -->
		<chien numeroCollier="C212343" />
		<chien numeroCollier="C456789">Spot</chien>
	</chiens>
	<chats>
		<chat numeroCollier="F456789">Felix</chat>
		<chat numeroCollier="F456789">Caramel</chat>
	</chats>
</animaux>
